In [2]:
import pandas as pd

df = pd.read_csv('../data/raw/results.csv')

df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [6]:
df["date"] = pd.to_datetime(df["date"])

df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df["day_of_week"] = df["date"].dt.day_name()
df["quarter"] = df["date"].dt.quarter
df["week"] = df["date"].dt.isocalendar().week

df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month,day,day_of_week,quarter,week
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False,1872,11,30,Saturday,4,48
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False,1873,3,8,Saturday,1,10
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False,1874,3,7,Saturday,1,10
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False,1875,3,6,Saturday,1,9
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False,1876,3,4,Saturday,1,9